---
- name: ansible project
  hosts: prod
  remote_user: ubuntu
  become: yes
  tasks: 
    - name: war filr
      copy:
        src: target/webfile-latest.war
        dest: /var/lib/tomcat9/webapps
        remote_src: yes
        owner: tomcat9
        group: tomcat9